name: Release project

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & publish release

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('.github/workflows/.depcache') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Configure Maven settings
        env:
          M2_SETTINGS: ${{ secrets.M2_SETTINGS }}
        run: printf "$M2_SETTINGS" > ~/.m2/settings.xml

      - name: Configure NPM settings
        env:
          NPMRC: ${{ secrets.NPMRC }}
        run: printf "$NPMRC" > ~/.npmrc

      - name: Tag name
        id: tag_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build docker image
        run: mvn spring-boot:build-image -Drevision=${{ steps.tag_name.outputs.SOURCE_TAG }}

      - name: Publish docker image
        env:
          DOCKER_REGISTRY: 'registry.intellective.com'
          DOCKER_USER: ${{ secrets.NEXUS_USER }}
          DOCKER_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          VERSION: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        run: ./publish-release.sh

      - name: Add container info to release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          isAppendBody: true
          body: |
            ### Containers
            registry.intellective.com/unity-origin/gw-app:${{ steps.tag_name.outputs.SOURCE_TAG }}
            registry.intellective.com/unity-origin/gw-app:release
